#!/usr/bin/env node
'use strict';

/**
 * Generates a static HTML page for every JSON file in content/pages/, using
 * templates/page-template.html as the shared shell. Run as the Netlify
 * build command (see netlify.toml) before the site is published.
 *
 * Never overwrites a hand-authored file: PROTECTED_NAMES blocks the known
 * bespoke pages and admin/ outright, and any other existing file is only
 * overwritten if it already carries the GENERATED_MARKER this script
 * writes into every page it creates, so a slug can never silently clobber
 * something a developer wrote by hand.
 */

const fs = require('fs');
const path = require('path');

const ROOT = path.resolve(__dirname, '..');
const PAGES_DIR = path.join(ROOT, 'content', 'pages');
const TEMPLATE_PATH = path.join(ROOT, 'templates', 'page-template.html');
const GENERATED_MARKER = '<!-- Generated by scripts/build-pages.js. Do not edit directly. Source: content/pages/ -->';

const PROTECTED_NAMES = new Set([
  'index.html',
  'restaurant.html',
  'menu.html',
  'takeaway.html',
  'cod-bar.html',
  'admin',
]);

function fail(message) {
  console.error('\n[build-pages] BUILD FAILED: ' + message + '\n');
  process.exit(1);
}

function escapeHtml(value) {
  return String(value == null ? '' : value).replace(/[&<>"']/g, function (c) {
    return { '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;', "'": '&#39;' }[c];
  });
}

function isGeneratedFile(filePath) {
  if (!fs.existsSync(filePath)) return true; // doesn't exist yet, safe to write
  return fs.readFileSync(filePath, 'utf8').indexOf(GENERATED_MARKER) !== -1;
}

function validateSlug(slug, sourceFile) {
  if (!/^[a-z0-9-]+$/.test(slug)) {
    fail(
      'Invalid filename "' + sourceFile + '" in content/pages/. ' +
      'Filenames (and therefore slugs) may only contain lowercase letters, numbers and hyphens.'
    );
  }
  if (PROTECTED_NAMES.has(slug) || PROTECTED_NAMES.has(slug + '.html')) {
    fail(
      'Slug "' + slug + '" (from content/pages/' + sourceFile + ') collides with a protected file/path ' +
      'and cannot be used. Protected: ' + Array.from(PROTECTED_NAMES).join(', ') +
      '. Rename the page (change its filename in content/pages/) to a different slug.'
    );
  }
}

function renderBody(body, sourceFile) {
  if (!Array.isArray(body)) return '';
  return body
    .map(function (p) { return '<p>' + escapeHtml(p) + '</p>'; })
    .join('\n        ');
}

function renderCta(ctaText, ctaHref) {
  if (!ctaText || !ctaHref) return '';
  return '<a href="' + escapeHtml(ctaHref) + '" class="btn btn-chili">' + escapeHtml(ctaText) + '</a>';
}

function main() {
  if (!fs.existsSync(TEMPLATE_PATH)) {
    fail('Template not found at ' + path.relative(ROOT, TEMPLATE_PATH));
  }
  const template = fs.readFileSync(TEMPLATE_PATH, 'utf8');

  if (!fs.existsSync(PAGES_DIR)) {
    console.log('[build-pages] No content/pages/ directory found, nothing to generate.');
    return;
  }

  const files = fs.readdirSync(PAGES_DIR).filter(function (f) { return f.endsWith('.json'); });

  if (files.length === 0) {
    console.log('[build-pages] No page JSON files found in content/pages/, nothing to generate.');
    return;
  }

  files.forEach(function (file) {
    const slug = file.replace(/\.json$/, '');
    validateSlug(slug, file);

    const jsonPath = path.join(PAGES_DIR, file);
    let data;
    try {
      data = JSON.parse(fs.readFileSync(jsonPath, 'utf8'));
    } catch (err) {
      fail('Could not parse content/pages/' + file + ': ' + err.message);
      return;
    }

    if (!data.title) fail('content/pages/' + file + ' is missing a required "title" field.');
    if (!data.meta_description) fail('content/pages/' + file + ' is missing a required "meta_description" field.');

    const outputName = slug + '.html';
    const outputPath = path.join(ROOT, outputName);

    if (!isGeneratedFile(outputPath)) {
      fail(
        'Refusing to overwrite "' + outputName + '": it already exists and was not created by this script. ' +
        'Choose a different filename for content/pages/' + file + ', or remove the conflicting file manually if it is stale.'
      );
    }

    const html = template
      .split('{{TITLE}}').join(escapeHtml(data.title))
      .split('{{META_DESCRIPTION}}').join(escapeHtml(data.meta_description))
      .split('{{HERO_IMAGE}}').join(escapeHtml(data.hero_image || ''))
      .split('{{HERO_ALT}}').join(escapeHtml(data.hero_alt || ''))
      .split('{{BODY_HTML}}').join(renderBody(data.body, file))
      .split('{{CTA_HTML}}').join(renderCta(data.cta_text, data.cta_href))
      .split('{{NAV_KEY}}').join(slug);

    fs.writeFileSync(outputPath, html);
    console.log('[build-pages] Generated ' + outputName + ' from content/pages/' + file);
  });
}

main();
